### ISSUE TITLE
Problems running SLRCPlus

### ISSUE THREAD

**Issue by HeyWeCome** [THUwangcy/ReChorus#35]
Hi Wang,
I met some problem when i try to run SLRCPlus on 'ml-1m'. 

The CMD command I input is:
`
python main.py --model_name SLRCPlus --emb_size 64 --lr 5e-4 --l2 1e-5 --dataset 'ml-1m'
`

The error is shown as:
<img width="728" alt="image" src="https://user-images.githubusercontent.com/30435835/182615030-d36fdae3-eeba-464f-9816-b85b9fa9fbc5.png">

Could you please give me some guidance? Thanks in advance.

**Comment by THUwangcy** [comment]
Hi, I found this is actually a bug. The KGReader should inherit from SeqReader instead of BaseReader (I isolated SeqReader from BaseReader before but forget that models using KG info also require history info). I have fixed it in the latest commit.

**Comment by HeyWeCome** [comment]
> Hi, I found this is actually a bug. The KGReader should inherit from SeqReader instead of BaseReader (I isolated SeqReader from BaseReader before but forget that models using KG info also require history info). I have fixed it in the latest commit.

Hi Wang, Thank you very much for your reply. I am sorry that the error is still not resolved after I pull the latest code. I have checked the slef.data when running SLRCPlus.py with ml-1m and it doesn't contain position information. Could you please check again?

**Comment by THUwangcy** [comment]
You can try to run with --regenerate 1 (ReChorus will load the previous dumped Reader by default).

**Comment by HeyWeCome** [comment]
Thanks, it works for me right now.
